services:
  app:
    image: 93minki/nextjs-dev:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./outer-data/outer-version.json:/app/outer-version.json
    environment:
      - NODE_ENV=development
    command: yarn dev
