FROM node:18-alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./

# yarn.lock 파일을 보고 Yarn에서 PnP 모드로 설정할 수 있기 때문에
# 명시적으로 node-modules 모드로 강제함.
RUN yarn config set nodeLinker node-modules && yarn install

COPY . .
COPY .env.development .env

ENV NODE_ENV=development
EXPOSE 3000
CMD ["yarn", "dev"]
