services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./outer-data/outer-version.json:/app/outer-version.json
    environment:
      - NODE_ENV=development
    command: yarn dev
