services:
  app:
    image: nextjs-json-test:dev-fa84444
    ports:
      - "3000:3000"
    volumes:
      - ./outer-data/outer-version.json:/usr/src/app/outer-version.json
    environment:
      - NODE_ENV=production
