name: Build Docker Image for Development Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create .env.development
        run: |
          echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> .env.development
          echo "GIST_URL=${{ secrets.GIST_URL }}" >> .env.development

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push to Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/nextjs-dev

          docker build -f Dockerfile.dev \
            -t $IMAGE:dev-${{ env.SHORT_SHA }} \
            -t $IMAGE:latest .

          docker push $IMAGE:dev-${{ env.SHORT_SHA }}
          docker push $IMAGE:latest
