name: Build Docker Image for Development Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create .env.development
        run: echo "${{ secrets.ENV }}" | tr '\r' '\n' > .env.development

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push to Docker Hub
        run: |
          docker build -f Dockerfile.dev \
            -t ${{ secrets.DOCKER_USER_NAME }}/nextjs-dev:dev-${{ env.SHORT_SHA }}
          docker push ${{ secrets.DOCKER_USER_NAME }}/nextjs-dev:dev-${{ env.SHORT_SHA }}