name: Build Docker Image for Devlopment Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image and export as .tar
        run: |
          docker build -f Dockerfile.dev \
            -t nextjs-dev:dev=${{ env.SHORT_SHA }} .
          docker save nextjs-dev:dev-${{ env.SHORT_SHA}} \
            -o nextjs-dev-${{ env.SHORT_SHA }}

      - name: Upload image tar to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev-image-${{ env.SHORT_SHA }}
          path: nextjs-dev-${{ env.SHORT_SHA }}.tar
