name: Build Production Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Write .env.production file
        run: echo "${{ secrets.ENV_PROD }}" > .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build production image and save as .tar
        run: |
          docker build -f Dockerfile.prod \
            -t nextjs-prod:prod-${{ env.SHORT_SHA }} .
          docker save nextjs-prod:prod-${{ env.SHORT_SHA }} \
            -o nextjs-prod-${{ env.SHORT_SHA }}.tar

      - name: Upload image tar
        uses: actions/upload-artifact@v4
        with:
          name: prod-image-${{ env.SHORT_SHA }}
          path: nextjs-prod-${{ env.SHORT_SHA }}.tar
